#include <configs/xilinx_zynqmp.h>
//#include <configs/platform-auto.h>

#define CONFIG_USB y
#define CONFIG_DM_USB y
#define CONFIG_DM_USB_GADGET y

#define CONFIG_USB_STORAGE y
#define CONFIG_USB_GADGET y
#define CONFIG_USB_GADGET_MANUFACTURER "U-Boot"
#define CONFIG_USB_GADGET_VENDOR_NUM 0x0
#define CONFIG_USB_GADGET_PRODUCT_NUM 0x0
#define CONFIG_USB_GADGET_VBUS_DRAW 2
#define CONFIG_USB_GADGET_DOWNLOAD y
#define CONFIG_USB y
#define CONFIG_DM_USB y
#define CONFIG_DM_USB_GADGET y

#define CONFIG_USB_DWC3 y
#define CONFIG_USB_DWC3_GADGET y

#define CONFIG_USB_STORAGE y
#define CONFIG_USB_GADGET y
#define CONFIG_USB_GADGET_MANUFACTURER "U-Boot"
#define CONFIG_USB_GADGET_VENDOR_NUM 0x0
#define CONFIG_USB_GADGET_PRODUCT_NUM 0x0
#define CONFIG_USB_GADGET_DWC2_OTG y
#define CONFIG_USB_GADGET_VBUS_DRAW 2
#define CONFIG_USB_GADGET_DUALSPEED y
#define CONFIG_USB_GADGET_DOWNLOAD y
